###################################
### MICROSERVICIO DE DELIVERIES ###
###################################

### CRUD DE DELIVERY

### Obtener las entregas
GET http://localhost:8001/deliveries


### Obtener las entregas por ID
GET http://localhost:8001/deliveries/1


### Crear un delivery

# Este es el endpoint utilizado por el microservicio de E-commerce para la creación 
# automática de un delivery, al cambiar el estado de una orden a "dispatched".

POST http://localhost:8001/deliveries
Content-Type: application/json

{
    "order":
    {
        "foreing_order_id": "order number provided by ecommerce microservice",
        "products": [{
                "sku": "unique id of product",
                "name": "product name",
                "qty": "product quantity"
            }]
    },
    "origin": {
        "address": "pickup address"
    },
    "destination": {
        "name": "customer name",
        "address": "customer address"
    }
}

### Obtener el seguimiento de una entrega

GET http://localhost:8001/deliveries/tracking
Content-Type: application/json

{
    "tracking_number": 1
}

### Eliminar una entrega

DELETE http://localhost:8001/deliveries/2
